# webpwnized/mutillidae:ldap

# Not an official repo
# Documentation: https://hub.docker.com/r/osixia/openldap
FROM osixia/openldap:latest

# Set up the LDAP configuration
ENV LDAP_ORGANISATION="Mutillidae"
ENV LDAP_DOMAIN="mutillidae.local"
ENV LDAP_ADMIN_PASSWORD="mutillidae"
ENV LDAP_BASE_DN="dc=mutillidae,dc=local"
ENV LDAP_TLS="false"
